{% set name = "gpg-tui" %}
{% set version = "0.11.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/orhun/gpg-tui/archive/v{{ version }}.tar.gz
  sha256: 741def01fe84ee20c3eac1cbbe2533e1a9c387832cab31b5d233062338254ce1

build:
  number: 0
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - cargo-bundle-licenses
    - pkg-config
  host:
    - gpgme
    - libgpg-error
  run:
    - gnupg

test:
  commands:
    - gpg-tui --help

about:
  home: https://github.com/orhun/gpg-tui
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: Manage your GnuPG keys with ease!
  dev_url: https://github.com/orhun/gpg-tui

extra:
  recipe-maintainers:
    - danielnachun
